CREATE TABLE EMPLOYEE (
    id INT PRIMARY KEY,
    name VARCHAR(255) NOT NULL
);

CREATE TABLE DEPARTMENT (
    id INT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    mandatory boolean,
    read_only boolean
);

CREATE TABLE MAP_EMPLOYEE_DEPARTMENT (
     id_employee INTEGER,
     id_department INTEGER,
     PRIMARY KEY (id_employee, id_department),
     FOREIGN KEY (id_employee) REFERENCES EMPLOYEE(id),
     FOREIGN KEY (id_department) REFERENCES DEPARTMENT(id)
);

CREATE SEQUENCE SEQUENCE_EMPLOYEE
    MINVALUE 1
    START WITH 1
    INCREMENT BY 1;

CREATE SEQUENCE SEQUENCE_DEPARTMENT
    MINVALUE 1
    START WITH 1
    INCREMENT BY 1;
